version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fp-ts
    versions:
    - 2.10.3
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.2
    - 5.24.0
    - 5.24.1
    - 5.30.0
    - 5.34.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
    - 9.0.2
    - 9.1.0
  - dependency-name: rxjs
    versions:
    - 7.0.0-beta.12
    - 7.0.0-beta.13
    - 7.0.0-beta.14
    - 7.0.0-beta.15
    - 7.0.0-rc.1
    - 7.0.0-rc.2
  - dependency-name: monocle-ts
    versions:
    - 2.3.8
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
